export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_FEED_SUCCESS = "GET_FEED_SUCCESS";

export const PROFILE_REQUEST_SENT = "PROFILE_REQUEST_SENT";
export const FEED_REQUEST_SENT = "FEED_REQUEST_SENT";

export const TWEETS_REQUEST_SENT = 'TWEETS_REQUEST_SENT';
export const TWEETS_ANE_REPLIES_REQUEST_SENT = 'TWEETS_ANE_REPLIES_REQUEST_SENT';
export const MEDIA_REQUEST_SENT = 'MEDIA_REQUEST_SENT';
export const LIKES_REQUEST_SENT = 'LIKES_REQUEST_SENT';

export const GET_TWEETS_SUCCESS = 'GET_TWEETS_SUCCESS';
export const GET_TWEETS_AND_REPLIES_SUCCESS = 'GET_TWEETS_AND_REPLIES_SUCCESS';
export const GET_MEDIA_SUCCESS = 'GET_MEDIA_SUCCESS';
export const GET_LIKES_SUCCESS = 'GET_LIKES_SUCCESS';


export const GET_MEDIA_POSTS = 'GET_MEDIA_POSTS';
export const GET_USER_LIKES = "GET_USER_LIKES";

export const GET_PINNED_POST = "GET_PINNED_POST";
export const ADD_PINNED_POST = "ADD_PINNED_POST";
export const REMOVE_PINNED_POST = "REMOVE_PINNED_POST";
export const TOGGLE_LIKE_PIN_POST = 'TOGGLE_LIKE_PIN_POST';
export const SET_UNPINNED_POSTS_LIKES = 'SET_UNPINNED_POSTS_LIKES'
export const SET_PINNED_POSTS_LIKES = 'SET_PINNED_POSTS_LIKES'

export const REFRESH_FEED = "REFRESH_FEED";
export const REFRESH_POST = "REFRESH_POST";

export const TOGGLE_LIKE_POST = "TOGGLE_LIKE_POST";

export const DELETE_POST = "DELETE_POST";
export const CREATE_COMMENT = "CREATE_COMMENT";

export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const FOLLOW_POST_USER = 'FOLLOW_POST_USER';
export const UNFOLLOW_POST_USER = 'UNFOLLOW_POST_USER';

export const EDIT_USER = "EDIT_USER";

export const GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS'
export const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS'

export const GET_USERS_POST_COUNT = 'GET_USERS_POST_COUNT';
export const ADD_USERS_POST_COUNT = 'ADD_USERS_POST_COUNT'
export const SUBTRACT_USERS_POST_COUNT = 'SUBTRACT_USERS_POST_COUNT'

export const SET_FEED_MESSAGE = 'SET_FEED_MESSAGE';
export const CLEAR_FEED_MESSAGE = 'CLEAR_FEED_MESSAGE';





