export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_FEED_SUCCESS = "GET_FEED_SUCCESS";

export const PROFILE_REQUEST_SENT = "PROFILE_REQUEST_SENT";
export const FEED_REQUEST_SENT = "FEED_REQUEST_SENT";

export const GET_TWEETS_AND_REPLIES = "GET_USER_TWEETS_AND_REPLIES";
export const GET_USER_LIKES = "GET_USER_LIKES";

export const GET_PINNED_POST = "GET_PINNED_POST";
export const ADD_PINNED_POST = "ADD_PINNED_POST";
export const REMOVE_PINNED_POST = "REMOVE_PINNED_POST";
export const TOGGLE_LIKE_PIN_POST = 'TOGGLE_LIKE_PIN_POST';

export const REFRESH_FEED = "REFRESH_FEED";
export const REFRESH_POST = "REFRESH_POST";

export const TOGGLE_LIKE_POST = "TOGGLE_LIKE_POST";

export const DELETE_POST = "DELETE_POST";

export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const FOLLOW_POST_USER = 'FOLLOW_POST_USER';
export const UNFOLLOW_POST_USER = 'UNFOLLOW_POST_USER';

export const EDIT_USER = "EDIT_USER";

export const GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS'
export const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS'
