export const CLEAR_TWEET_DETAILS = "CLEAR_TWEET_DETAILS";
export const GET_TWEET_DETAILS = "GET_TWEET_DETAILS";
export const LIKE_TWEET_DETAILS = "LIKE_TWEET_DETAILS";

export const SET_LOADING = "SET_LOADING";
export const TWEET_DETAILS_REQUEST = "TWEET_DETAILS_REQUEST";
export const TWEET_DETAILS_SUCCESS = "TWEET_DETAILS_SUCCESS";
export const TWEET_DETAILS_FAILED = "TWEET_DETAILS_FAILED";

export const COMMENTS_REQUEST_SENT = "COMMENTS_REQUEST_SENT";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const LIKE_COMMENT_DETAILS = "LIKE_COMMENT_DETAILS";
export const LIKE_COMMENT = "LIKE_COMMENT";
export const LIKE_TWEET = "LIKE_TWEET";

export const PIN_COMMENT = "PIN_COMMENT";

export const DELETE_POST = "DELETE_POST";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_REPLIED_TO_POST = "DELETE_REPLIED_TO_POST";
export const TWEET_DETAILS_FOLLOW_USER = "TWEET_DETAILS_FOLLOW_USER";
export const TWEET_DETAILS_UNFOLLOW_USER = "TWEET_DETAILS_UNFOLLOW_USER";

export const REFRESH_POST = "REFRESH_POST";

export const LIKE_REPLIED_TO_POST = "LIKE_REPLIED_TO_POST";

export const GET_THREAD_POSTS = "GET_THREAD_POSTS";
