export const CLEAR_TWEET_DETAILS = 'CLEAR_TWEET_DETAILS';
export const GET_TWEET_DETAILS = 'GET_TWEET_DETAILS'
export const LIKE_TWEET_DETAILS = 'LIKE_TWEET_DETAILS'

export const SET_LOADING = 'SET_LOADING'
export const TWEET_DETAILS_REQUEST = 'TWEET_DETAILS_REQUEST';
export const TWEET_DETAILS_SUCCESS = 'TWEET_DETAILS_SUCCESS';

export const GET_COMMENTS = 'GET_COMMENTS';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const LIKE_COMMENT_DETAILS = 'LIKE_COMMENT_DETAILS'
export const LIKE_COMMENT = 'LIKE_COMMENT'
export const LIKE_TWEET = 'LIKE_TWEET';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_REPLIED_TO_POST = 'DELETE_REPLIED_TO_POST';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';

export const REFRESH_POST = 'REFRESH_POST';

export const LIKE_REPLIED_TO_POST = 'LIKE_REPLIED_TO_POST'

export const GET_THREAD_POSTS = 'GET_THREAD_POSTS';
